name: pytest

on:
  push:
    branches:
      - "main"
    paths:
      - "python/submit/**.py"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "python/submit/**.py"

defaults:
  run:
    shell: bash -e {0}

jobs:
  check:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Change directory
        run: cd python/submit

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.9"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest
