[project]
name = "submit"
version = "0.1.0"
description = "Extract code block which should be submitted to regulatory agency."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chardet>=5.2.0",
]

[project.scripts]
submit = "submit:main"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.8.3",
]

[tool.ruff]
line-length = 120
